# Generated by Django 3.1.7 on 2021-03-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lname',
            new_name='last_name',
        ),
    ]
